### ISSUE TITLE
Bootcamp Feedback TODO

### ISSUE THREAD

**Issue by danilolab** [jesszanon/Kidelicia-Burguer#1]
Deixo como sugestão os seguintes tópicos:
- [ ] Aprofundar os estudos no angular
- [ ] Escrever os testes unitários
- [ ] Estudar um pouco mais das propriedades
- [ ] Ver conceitos de flex-layout
- [ ] Criar um projeto pessoal, para crianças e/ou familiares e publicar no git
- [ ] Refazer alguns exercícios da GYM focados em layout e backend
- [ ] Recomendação de sites: https://www.hackerrank.com/, https://leetcode.com/ e https://www.codewars.com/
